name: Build Mypyc

on:
  pull_request:
    branches:
      - master
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypyc:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        pyversion: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
        
    concurrency:
      group: mypyc
      cancel-in-progress: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}  # Check out the PR branch

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyversion }}

    - name: Install Mypyc
      run: pip install mypy[mypyc] types-requests

    - name: Run Mypyc
      run: make mypyc

    - name: Check for changes
      id: changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes_detected=true" >> $GITHUB_ENV
        else
          echo "changes_detected=false" >> $GITHUB_ENV
        fi

    - name: Commit changes
      if: env.changes_detected == 'true'
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "chore: \`mypyc\` for python${{ matrix.pyversion }}"
        git push
