name: MyPy

on: pull_request
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        pyversion: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Python (faster than using Python container)
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}

    - name: Install MyPy
      run: |
        python -m pip install --upgrade pip
        pip install mypy

    - name: Run MyPy
      run: mypy . --strict --pretty --show-error-codes --show-error-context --install-types --non-interactive --ignore-missing-imports
